# Generated by Django 5.0.1 on 2024-01-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
