# Generated by Django 5.0.1 on 2024-02-27 08:20

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_field',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='post_images/'),
        ),
    ]
