# Generated by Django 5.0.1 on 2024-03-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0010_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
