# Generated by Django 5.0.1 on 2024-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0011_rename_data_of_birth_account_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوژی'), ('زبان برنامه نویسی', 'زبان برنامه نویسی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بلاکچین', 'بلاکچین'), ('سایر', 'سایر')], default='سایر', max_length=30),
        ),
    ]
